app/pages/PersonalizedPlan.tsx: Expected corresponding JSX closing tag for <Card>. (121:10)

  119 |               Concepts explained using your hobbies to make learning more relatable.
  120 |             </p>
> 121 |           </div>
      |           ^
  122 |         </div>
  123 |
  124 |         <Card className="p-6">
    at toParseError (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parse-error.ts:95:45)
    at TypeScriptParserMixin.raise (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/tokenizer/index.ts:1503:19)
    at TypeScriptParserMixin.jsxParseElementAt (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/plugins/jsx/index.ts:527:18)
    at TypeScriptParserMixin.jsxParseElementAt (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/plugins/jsx/index.ts:483:34)
    at TypeScriptParserMixin.jsxParseElementAt (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/plugins/jsx/index.ts:483:34)
    at TypeScriptParserMixin.jsxParseElementAt (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/plugins/jsx/index.ts:483:34)
    at TypeScriptParserMixin.jsxParseElement (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/plugins/jsx/index.ts:559:19)
    at TypeScriptParserMixin.parseExprAtom (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/plugins/jsx/index.ts:573:21)
    at TypeScriptParserMixin.parseExprSubscripts (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:734:23)
    at TypeScriptParserMixin.parseUpdate (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:713:21)
    at TypeScriptParserMixin.parseMaybeUnary (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:675:23)
    at TypeScriptParserMixin.parseMaybeUnary (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/plugins/typescript/index.ts:3855:20)
    at TypeScriptParserMixin.parseMaybeUnaryOrPrivate (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:409:14)
    at TypeScriptParserMixin.parseExprOps (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:421:23)
    at TypeScriptParserMixin.parseMaybeConditional (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:376:23)
    at TypeScriptParserMixin.parseMaybeAssign (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:301:21)
    at fn (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/plugins/typescript/index.ts:3708:23)
    at TypeScriptParserMixin.tryParse (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/util.ts:174:20)
    at TypeScriptParserMixin.parseMaybeAssign (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/plugins/typescript/index.ts:3707:20)
    at callback (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:257:12)
    at TypeScriptParserMixin.allowInAnd (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:3192:12)
    at TypeScriptParserMixin.parseMaybeAssignAllowIn (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:256:17)
    at TypeScriptParserMixin.parseMaybeAssignAllowInOrVoidPattern (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:3306:17)
    at TypeScriptParserMixin.parseParenAndDistinguishExpression (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:1813:16)
    at TypeScriptParserMixin.parseExprAtom (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:1162:21)
    at TypeScriptParserMixin.parseExprAtom (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/plugins/jsx/index.ts:583:22)
    at TypeScriptParserMixin.parseExprSubscripts (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:734:23)
    at TypeScriptParserMixin.parseUpdate (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:713:21)
    at TypeScriptParserMixin.parseMaybeUnary (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:675:23)
    at TypeScriptParserMixin.parseMaybeUnary (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/plugins/typescript/index.ts:3855:20)
    at TypeScriptParserMixin.parseMaybeUnaryOrPrivate (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:409:14)
    at TypeScriptParserMixin.parseExprOps (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:421:23)
    at TypeScriptParserMixin.parseMaybeConditional (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:376:23)
    at TypeScriptParserMixin.parseMaybeAssign (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:301:21)
    at TypeScriptParserMixin.parseMaybeAssign (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/plugins/typescript/index.ts:3727:22)
    at TypeScriptParserMixin.parseExpressionBase (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:226:23)
    at callback (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:217:39)
    at TypeScriptParserMixin.allowInAnd (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:3187:16)
    at TypeScriptParserMixin.parseExpression (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:217:17)
    at TypeScriptParserMixin.parseReturnStatement (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/statement.ts:1110:28)
    at TypeScriptParserMixin.parseStatementContent (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/statement.ts:538:21)
    at TypeScriptParserMixin.parseStatementContent (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/plugins/typescript/index.ts:3185:20)
    at TypeScriptParserMixin.parseStatementLike (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/statement.ts:477:17)
    at TypeScriptParserMixin.parseStatementListItem (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/statement.ts:426:17)
    at TypeScriptParserMixin.parseBlockOrModuleBlockBody (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/statement.ts:1439:16)
    at TypeScriptParserMixin.parseBlockBody (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/statement.ts:1412:10)
    at TypeScriptParserMixin.parseBlock (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/statement.ts:1380:10)
    at TypeScriptParserMixin.parseFunctionBody (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:2616:24)
    at TypeScriptParserMixin.parseFunctionBodyAndFinish (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:2585:10)
    at TypeScriptParserMixin.parseFunctionBodyAndFinish (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/plugins/typescript/index.ts:2646:20)
❌ [vite] Internal Server Error
app/pages/PersonalizedPlan.tsx: Expected corresponding JSX closing tag for <Card>. (121:10)

  119 |               Concepts explained using your hobbies to make learning more relatable.
  120 |             </p>
> 121 |           </div>
      |           ^
  122 |         </div>
  123 |
  124 |         <Card className="p-6">
    at toParseError (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parse-error.ts:95:45)
    at TypeScriptParserMixin.raise (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/tokenizer/index.ts:1503:19)
    at TypeScriptParserMixin.jsxParseElementAt (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/plugins/jsx/index.ts:527:18)
    at TypeScriptParserMixin.jsxParseElementAt (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/plugins/jsx/index.ts:483:34)
    at TypeScriptParserMixin.jsxParseElementAt (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/plugins/jsx/index.ts:483:34)
    at TypeScriptParserMixin.jsxParseElementAt (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/plugins/jsx/index.ts:483:34)
    at TypeScriptParserMixin.jsxParseElement (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/plugins/jsx/index.ts:559:19)
    at TypeScriptParserMixin.parseExprAtom (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/plugins/jsx/index.ts:573:21)
    at TypeScriptParserMixin.parseExprSubscripts (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:734:23)
    at TypeScriptParserMixin.parseUpdate (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:713:21)
    at TypeScriptParserMixin.parseMaybeUnary (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:675:23)
    at TypeScriptParserMixin.parseMaybeUnary (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/plugins/typescript/index.ts:3855:20)
    at TypeScriptParserMixin.parseMaybeUnaryOrPrivate (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:409:14)
    at TypeScriptParserMixin.parseExprOps (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:421:23)
    at TypeScriptParserMixin.parseMaybeConditional (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:376:23)
    at TypeScriptParserMixin.parseMaybeAssign (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:301:21)
    at fn (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/plugins/typescript/index.ts:3708:23)
    at TypeScriptParserMixin.tryParse (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/util.ts:174:20)
    at TypeScriptParserMixin.parseMaybeAssign (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/plugins/typescript/index.ts:3707:20)
    at callback (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:257:12)
    at TypeScriptParserMixin.allowInAnd (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:3192:12)
    at TypeScriptParserMixin.parseMaybeAssignAllowIn (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:256:17)
    at TypeScriptParserMixin.parseMaybeAssignAllowInOrVoidPattern (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:3306:17)
    at TypeScriptParserMixin.parseParenAndDistinguishExpression (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:1813:16)
    at TypeScriptParserMixin.parseExprAtom (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:1162:21)
    at TypeScriptParserMixin.parseExprAtom (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/plugins/jsx/index.ts:583:22)
    at TypeScriptParserMixin.parseExprSubscripts (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:734:23)
    at TypeScriptParserMixin.parseUpdate (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:713:21)
    at TypeScriptParserMixin.parseMaybeUnary (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:675:23)
    at TypeScriptParserMixin.parseMaybeUnary (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/plugins/typescript/index.ts:3855:20)
    at TypeScriptParserMixin.parseMaybeUnaryOrPrivate (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:409:14)
    at TypeScriptParserMixin.parseExprOps (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:421:23)
    at TypeScriptParserMixin.parseMaybeConditional (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:376:23)
    at TypeScriptParserMixin.parseMaybeAssign (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:301:21)
    at TypeScriptParserMixin.parseMaybeAssign (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/plugins/typescript/index.ts:3727:22)
    at TypeScriptParserMixin.parseExpressionBase (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:226:23)
    at callback (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:217:39)
    at TypeScriptParserMixin.allowInAnd (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:3187:16)
    at TypeScriptParserMixin.parseExpression (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:217:17)
    at TypeScriptParserMixin.parseReturnStatement (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/statement.ts:1110:28)
    at TypeScriptParserMixin.parseStatementContent (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/statement.ts:538:21)
    at TypeScriptParserMixin.parseStatementContent (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/plugins/typescript/index.ts:3185:20)
    at TypeScriptParserMixin.parseStatementLike (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/statement.ts:477:17)
    at TypeScriptParserMixin.parseStatementListItem (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/statement.ts:426:17)
    at TypeScriptParserMixin.parseBlockOrModuleBlockBody (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/statement.ts:1439:16)
    at TypeScriptParserMixin.parseBlockBody (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/statement.ts:1412:10)
    at TypeScriptParserMixin.parseBlock (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/statement.ts:1380:10)
    at TypeScriptParserMixin.parseFunctionBody (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:2616:24)
    at TypeScriptParserMixin.parseFunctionBodyAndFinish (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/parser/expression.ts:2585:10)
    at TypeScriptParserMixin.parseFunctionBodyAndFinish (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/src/plugins/typescript/index.ts:2646:20)
❌ 6:35:29 PM [vite] Internal server error: app/pages/PersonalizedPlan.tsx: Expected corresponding JSX closing tag for <Card>. (121:10)

  119 |               Concepts explained using your hobbies to make learning more relatable.
  120 |             </p>
> 121 |           </div>
      |           ^
  122 |         </div>
  123 |
  124 |         <Card className="p-6">
  Plugin: vite:react-babel
  File: app/pages/PersonalizedPlan.tsx:121:10
  119|                Concepts explained using your hobbies to make learning more relatable.
  120|              </p>
  121|            </div>
     |            ^
  122|          </div>
  123|  
      at toParseError (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parse-error.ts:95:45)
      at TypeScriptParserMixin.raise (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/tokenizer/index.ts:1503:19)
      at TypeScriptParserMixin.jsxParseElementAt (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/plugins/jsx/index.ts:527:18)
      at TypeScriptParserMixin.jsxParseElementAt (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/plugins/jsx/index.ts:483:34)
      at TypeScriptParserMixin.jsxParseElementAt (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/plugins/jsx/index.ts:483:34)
      at TypeScriptParserMixin.jsxParseElementAt (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/plugins/jsx/index.ts:483:34)
      at TypeScriptParserMixin.jsxParseElement (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/plugins/jsx/index.ts:559:19)
      at TypeScriptParserMixin.parseExprAtom (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/plugins/jsx/index.ts:573:21)
      at TypeScriptParserMixin.parseExprSubscripts (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/expression.ts:734:23)
      at TypeScriptParserMixin.parseUpdate (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/expression.ts:713:21)
      at TypeScriptParserMixin.parseMaybeUnary (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/expression.ts:675:23)
      at TypeScriptParserMixin.parseMaybeUnary (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/plugins/typescript/index.ts:3855:20)
      at TypeScriptParserMixin.parseMaybeUnaryOrPrivate (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/expression.ts:409:14)
      at TypeScriptParserMixin.parseExprOps (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/expression.ts:421:23)
      at TypeScriptParserMixin.parseMaybeConditional (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/expression.ts:376:23)
      at TypeScriptParserMixin.parseMaybeAssign (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/expression.ts:301:21)
      at fn (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/plugins/typescript/index.ts:3708:23)
      at TypeScriptParserMixin.tryParse (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/util.ts:174:20)
      at TypeScriptParserMixin.parseMaybeAssign (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/plugins/typescript/index.ts:3707:20)
      at callback (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/expression.ts:257:12)
      at TypeScriptParserMixin.allowInAnd (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/expression.ts:3192:12)
      at TypeScriptParserMixin.parseMaybeAssignAllowIn (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/expression.ts:256:17)
      at TypeScriptParserMixin.parseMaybeAssignAllowInOrVoidPattern (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/expression.ts:3306:17)
      at TypeScriptParserMixin.parseParenAndDistinguishExpression (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/expression.ts:1813:16)
      at TypeScriptParserMixin.parseExprAtom (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/expression.ts:1162:21)
      at TypeScriptParserMixin.parseExprAtom (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/plugins/jsx/index.ts:583:22)
      at TypeScriptParserMixin.parseExprSubscripts (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/expression.ts:734:23)
      at TypeScriptParserMixin.parseUpdate (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/expression.ts:713:21)
      at TypeScriptParserMixin.parseMaybeUnary (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/expression.ts:675:23)
      at TypeScriptParserMixin.parseMaybeUnary (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/plugins/typescript/index.ts:3855:20)
      at TypeScriptParserMixin.parseMaybeUnaryOrPrivate (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/expression.ts:409:14)
      at TypeScriptParserMixin.parseExprOps (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/expression.ts:421:23)
      at TypeScriptParserMixin.parseMaybeConditional (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/expression.ts:376:23)
      at TypeScriptParserMixin.parseMaybeAssign (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/expression.ts:301:21)
      at TypeScriptParserMixin.parseMaybeAssign (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/plugins/typescript/index.ts:3727:22)
      at TypeScriptParserMixin.parseExpressionBase (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/expression.ts:226:23)
      at callback (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/expression.ts:217:39)
      at TypeScriptParserMixin.allowInAnd (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/expression.ts:3187:16)
      at TypeScriptParserMixin.parseExpression (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/expression.ts:217:17)
      at TypeScriptParserMixin.parseReturnStatement (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/statement.ts:1110:28)
      at TypeScriptParserMixin.parseStatementContent (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/statement.ts:538:21)
      at TypeScriptParserMixin.parseStatementContent (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/plugins/typescript/index.ts:3185:20)
      at TypeScriptParserMixin.parseStatementLike (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/statement.ts:477:17)
      at TypeScriptParserMixin.parseStatementListItem (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/statement.ts:426:17)
      at TypeScriptParserMixin.parseBlockOrModuleBlockBody (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/statement.ts:1439:16)
      at TypeScriptParserMixin.parseBlockBody (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/statement.ts:1412:10)
      at TypeScriptParserMixin.parseBlock (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/statement.ts:1380:10)
      at TypeScriptParserMixin.parseFunctionBody (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/expression.ts:2616:24)
      at TypeScriptParserMixin.parseFunctionBodyAndFinish (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/parser/expression.ts:2585:10)
      at TypeScriptParserMixin.parseFunctionBodyAndFinish (node_modules/.pnpm/@babel+parser@7.28.4/node_modules/@babel/parser/plugins/typescript/index.ts:2646:20)